name: Build and push docker image

on:
    workflow_call:
        inputs:
            tagversion:
                required: true
                type: string
            folder:
                required: true
                type: string
        secrets:
            DOCKERHUB_USERNAME:
                required: true
            DOCKERHUB_TOKEN:
                required: true

jobs:
    build-and-push-docker-image:
        name: "Build and push to docker hub"
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -   name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: Build and push Docker images
                uses: docker/build-push-action@v2.7.0
                with:
                    context: ${{ inputs.folder }}
                    tags: |
                        giuseppemorelli/php-ci-cd:${{ inputs.tagversion }}
                    push: ${{ github.ref == 'refs/heads/main' }}

            -   name: Image digest
                run: echo ${{ steps.docker_build.outputs.digest }}

