name: 8.1 on debian

on:
    push:
        branches:
            - main
    workflow_dispatch: ~

jobs:
    build-and-push-docker-image:
        name: "Build 8.1 on push to docker hub"
        uses: giuseppemorelli/docker-php-ci-cd/.github/workflows/build_and_push.yml@main
        with:
            tagversion: '8.1'
            folder: './php-8.1-debian'
        secrets:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
